apiVersion: v1
kind: ReplicationController
metadata:
  name: nginxs
spec:
  replicas: 5
  selector:
    app: demo
  template:
    metadata:
      name: demo
      labels:
        app: demo
    spec:
      containers:
        - name: nginxs
          image: nginx
          ports:
            - containerPort: 80
              name: ngin

